### ISSUE TITLE
Unable to send arrow keys

### ISSUE THREAD

**Issue by claytondukes** [jonkeane/keypi#1]
Hi, thanks for making this!

I'm unable to send arrow keys, e.g.:

(down arrow example below)

```
root@rpi [client]:(main)# keypi input custom
Enter your value: ^[[B
blasting...
Traceback (most recent call last):
  File "/usr/local/bin/keypi", line 33, in <module>
    sys.exit(load_entry_point('keypi', 'console_scripts', 'keypi')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/keypi/keypi/cli.py", line 34, in input_custom
    kb.custom_input()
  File "/root/keypi/keypi/client/client.py", line 82, in custom_input
    self.update_keys(keymap.convert(char), 1)
  File "/root/keypi/keypi/client/keymap.py", line 192, in convert
    return key_table[evdev_keycode]
KeyError: 'KEY_\x1b'
```

**Comment by jonkeane** [comment]
First, I should mention I'm not actually using this or really maintaining it anymore — so I wouldn't be surprised if things don't work.

But the `keypi input custom` mode typically takes characters one at a time, and the map between the shell-escaped values (`\x1b`) you see here aren't in the keymap. One thing you could try for this is to try to enter `{down}` at the `custom` input prompt (see https://github.com/jonkeane/keypi/blob/485353fdcc3d28b0f2f729908f018147a88a959b/keypi/client/keymap.py#L204-L205 for what's going on here)

[The keytable](https://github.com/jonkeane/keypi/blob/485353fdcc3d28b0f2f729908f018147a88a959b/keypi/client/keymap.py#L15-L177) might also be helpful for which non-character keys are mapped + what they are called.
